#!/usr/bin/env ruby
require 'net/http'
require 'json'
require 'pp'

data=JSON.parse(File.read(ARGV[0]))
#pp data
#data=JSON.parse(Net::HTTP.get(URI('https://api.discogs.com/releases/5364191')))
data["artists"].each{|x|puts "ARTIST=#{x["name"]}"}
puts "YEAR=#{data["year"]}"
puts "DATE=#{data["released"]}"
data["labels"].each{|x|puts "ORGANIZATION=#{x["name"]}"}
data["labels"].each{|x|puts "CATALOGNUMBER=#{x["catno"]}"}
puts "TRACKTOTAL=#{data["tracklist"].count}"
data["tracklist"].each{|x|puts "#{x["position"]}. TITLE=#{x["title"]}"}
#pp data["tracklist"]

