#!/usr/bin/env ruby
require 'net/http'
require 'json'
require 'pp'

data=JSON.parse(File.read(ARGV[0]))
#data=JSON.parse(Net::HTTP.get(URI('https://api.discogs.com/releases/5364191')))
#pp data
data["results"].each{|r|
  puts "#{r["master_id"]} #{r["id"]} #{r["title"]} (#{r["year"]}) #{r["format"]} #{r["country"]}"
}
# pp data
